@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu May 12 08:49:13 -0400 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 8b116b0f2b204b4fb3146b9f7187529e --incr --debug typical --relax --mt 2 -L xil_defaultlib -L lib_pkg_v1_0_2 -L lib_cdc_v1_0_2 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_4 -L axi_iic_v2_1_0 -L dist_mem_gen_v8_0_13 -L blk_mem_gen_v8_4_4 -L lib_bmg_v1_0_13 -L axi_traffic_gen_v3_0_10 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot axi_iic_0_exdes_tb_behav xil_defaultlib.axi_iic_0_exdes_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 8b116b0f2b204b4fb3146b9f7187529e --incr --debug typical --relax --mt 2 -L xil_defaultlib -L lib_pkg_v1_0_2 -L lib_cdc_v1_0_2 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_4 -L axi_iic_v2_1_0 -L dist_mem_gen_v8_0_13 -L blk_mem_gen_v8_4_4 -L lib_bmg_v1_0_13 -L axi_traffic_gen_v3_0_10 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot axi_iic_0_exdes_tb_behav xil_defaultlib.axi_iic_0_exdes_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
